### ISSUE TITLE
error/multiple_error_types 3

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [EyesCrypto-Insights/rust-by-example-vn#16]
1. [wrap_error.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/multiple_error_types/wrap_error.md)
2. [and_then.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/option_unwrap/and_then.md)

**Comment by duonghb53** [comment]
PR: https://github.com/nebula-labs/rust-by-example-vn/pull/22
