### ISSUE TITLE
error/option_unwrap

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [EyesCrypto-Insights/rust-by-example-vn#17]
1. [map.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/option_unwrap/map.md)
2. [question_mark.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/option_unwrap/question_mark.md)

**Comment by HongThaiPham** [comment]
[map.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/option_unwrap/map.md) done in [https://github.com/nebula-labs/rust-by-example-vn/commit/e07ca88c2569e78df387ef990e357fd8f1e5d7c6](https://github.com/nebula-labs/rust-by-example-vn/commit/e07ca88c2569e78df387ef990e357fd8f1e5d7c6)

**Comment by HongThaiPham** [comment]
[question_mark.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/error/option_unwrap/question_mark.md) done in [https://github.com/nebula-labs/rust-by-example-vn/commit/8d175e1209327ade224d1f49952e0bfe0b6769cc](https://github.com/nebula-labs/rust-by-example-vn/commit/8d175e1209327ade224d1f49952e0bfe0b6769cc)
