### ISSUE TITLE
Finish src/attribute

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [EyesCrypto-Insights/rust-by-example-vn#2]
Translate: https://github.com/nebula-labs/rust-by-example-vn/tree/main/src/attribute

From: https://github.com/rust-lang/rust-by-example/tree/master/src/attribute

- [ ] cfg/custom.md (Duong)
- [ ] cfg.md (Duong)
- [ ] crate.md (Dung)
- [ ] unused.md (Dung)

**Comment by duonghb53** [comment]
PR translate attribute cfg & custom cfg: 
https://github.com/nebula-labs/rust-by-example-vn/pull/3

**Comment by frenkie-ng** [comment]
PR translate attribute crate & unused
#4
