### ISSUE TITLE
fn/closures 2

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [EyesCrypto-Insights/rust-by-example-vn#30]
1. [closure_examples.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/fn/closures/closure_examples.md)
2. [input_functions.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/fn/closures/input_functions.md)

**Comment by HongThaiPham** [comment]
close #30
