### ISSUE TITLE
Translate cargo

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [EyesCrypto-Insights/rust-by-example-vn#5]
https://github.com/nebula-labs/rust-by-example-vn/tree/main/src/cargo

1. build_scripts.md (Duong)
2. conventions.md (Duong)
3. deps.md (Dung)
4. test.md (Dung)
5. [raw_identifiers.md](https://github.com/nebula-labs/rust-by-example-vn/blob/main/src/compatibility/raw_identifiers.md) (Vu)

**Comment by duonghb53** [comment]
1. PR translate `attribute.md` #7 missing
2. PR translate `cargo.md, build_scripts.md, conventions.md` #8

**Comment by nghuyenthevinh2000** [comment]
@SkyTik bạn có thể xem bản gốc tiếng anh ở đây nhé: https://github.com/rust-lang/rust-by-example/blob/master/src/compatibility/raw_identifiers.md
